### PR TITLE
Fix safe area mobile, Fix cuttoff of safearea mobile, Set sidebar to …

### LINKED ISSUE #161: sidebar moves into "safe-area" in landscape on iPhone after the mobile-scroll patch.
Similar to the issue fixed by this PR: https://github.com/nasa-petal/bidara-deep-chat/pull/53

### PR DESCRIPTION
**Pull request by jackitaliano**
# Fix safe area mobile, Fix cuttoff of safearea mobile, Set sidebar to fixed size
- Prevent chats, menu, nav buttons, etc. on mobile from appearing hidden in the safe area of mobile devices
- Remove cuttoff of nav and sidebar from safe area (would just be dark/white inside of safe area instead of ui
- Set navbar to fixed size
  - Seems to match with other sidebar UX more (e.g. other chat bots, iOS) rather than a percentage of screen
  
  Resolves #161

### CODE REVIEW

File: src/components/Sidebar.svelte [hunk 1]
```diff
@@ -11,6 +11,7 @@
   import Chat from './Chat.svelte'
 
   function isSmallScreen() {
+    console.log("screen size:", window.innerWidth)
```
Comment (bruffridge) [inline src/components/Sidebar.svelte:14]: did you mean to leave this in?
